name: Deploy Production
on: [push, pull_request]
#  push:
#    tags:
#      - v*
#    branches:
#      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Run Tests
        run: go test -v ./...

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./... -o ./bin

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: './bin'
  deploy-production:
    name: Deploy app to Production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only --config fly-production.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}