name: Homework module 5
on: [push, pull_request]
#  push:
#    tags:
#      - v*
#    branches:
#      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run Tests
        run: go test -v ./...

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build
        run: go build -v -o bin/homework-${{ matrix.os }} ./...

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: 'bin/'
          name: homework-${{ matrix.os }}

  deploy:
    name: Deploy app to Production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    needs: [build, test]
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: homework-${{ matrix.os }}

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: homework-${{ matrix.os }}
          host: ${{ secrets.ADDRESS }}
          remote: "/home/${{ secrets.USER }}"
          port: 22
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
